# Generated by Django 4.2.2 on 2024-09-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_list", "0003_alter_mailingsettings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="server_response",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Ответ почтового сервера, если он был",
            ),
        ),
        migrations.AlterField(
            model_name="mailingsettings",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("started", "запущена"),
                    ("completed", "завершена"),
                ],
                default="создана",
                max_length=15,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
