# Generated by Django 4.2.2 on 2024-09-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_list", "0004_attempt_server_response_alter_mailingsettings_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingsettings",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="mailingsettings",
            name="period",
            field=models.CharField(
                choices=[
                    ("per_day", "раз в день"),
                    ("per_week", "раз в неделю"),
                    ("per_month", "раз в месяц"),
                ],
                default="раз в месяц",
                max_length=15,
                verbose_name="Период рассылки",
            ),
        ),
    ]
