# Generated by Django 4.2.2 on 2024-09-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_list", "0005_alter_mailingsettings_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="last_attempt_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время последней попытки рассылки",
            ),
        ),
    ]
