# Generated by Django 4.2.2 on 2024-09-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, null=True, verbose_name="Содержимое статьи"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/%Y/%m",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "date_published",
                    models.DateField(auto_now_add=True, verbose_name="Дата публикации"),
                ),
                (
                    "count_views",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в блоге",
                "verbose_name_plural": "Записи в блоге",
                "ordering": ["date_published"],
            },
        ),
    ]
